### ISSUE TITLE
pvaSrv does not always get first monitor

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvaSrv#1]
*Reported from Marty Kraimer <mrkraimer_AT_comcast.net>:*
In a message to me Matej said:
> However I’ve noticed one thing… if I run exampleDatabase and then do
> eget -m enum01
> I do not get the first (immediate) monitor at all?
> Do you get it ?

It was a problem in pvaSrv.
Note that it does not happen for local provider in pvDatabase.

The fix is:
```diff
mrk> pwd
/home/hg/pvaSrv/src/dbPv/3.14
mrk> hg diff dbPvMonitor.cpp
diff -r 00bf5c7e66fe src/dbPv/3.14/dbPvMonitor.cpp
--- a/src/dbPv/3.14/dbPvMonitor.cpp    Mon Feb 09 11:44:46 2015 -0600
+++ b/src/dbPv/3.14/dbPvMonitor.cpp    Wed Feb 18 07:07:40 2015 -0500
@@ -270,7 +270,7 @@
         }
         index = overrunBitSet->nextSetBit(index+1);
     }
-    if(bitSet->nextSetBit(0)>=0) {
+    if(firstTime || bitSet->nextSetBit(0)>=0) {
         nextElement =getFree();
         if(nextElement) {
             PVStructure::shared_pointer pvNext = nextElement->pvStructurePtr;
mrk>
```
Ralph,
Can you take care of this?
You may have a different way to fix the problem.
Marty

**Comment by dhickin** [comment]
<p>Marty's suggested fix does ensure the first event for the monitor is seen. An alternative, possibly cleaner is to move</p>
<code>
    if(firstTime) {
        firstTime = false;
        bitSet->clear();
        bitSet->set(0);
    }
</code>
<p>above</p>
<code>
    if(bitSet->nextSetBit(0)>=0) {
</code>
<p>in eventCallback().</p>

<p>However the issue affects not just the first monitor event, but also the first monitor event each time the monitor is started. So a better solution will be to clear/set these bits then. Also I think the overflow bitset needs clearing at this point. This is how the pvDatabase monitoring works.</p>

<p>When I tried this I found other issues with stopping and starting monitors and with the number of free elements  - I've raised separate issues for these (issues #23 and #24). With the above fix and the fixes for these latter issues I'm able to get first event and events for subsequent events on each update initially and after stopping and starting the monitor.</p>

<p>I'll add the equivalent code for 3.15 and generate the pull request along with fixes for #23 and #24.</p>
