### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by NickeZ** [epics-base/pvaSrv#20]
Hey everyone, quick question do I need to install "obsolete" pvIOCCPP to compile pvaSrv?

```
../../src/dbGroup/dbGroup.cpp:14:37: fatal error: pv/channelProviderLocal.h: No such file or directory
 #include <pv/channelProviderLocal.h>
```

**Comment by dhickin** [comment]
<p>No, not as of 4.4.0. So if your building 4.4.0 or 4.5.0 then you will be fine.</p>

<p>However, it looks like you're trying to build dbGroup. dbGroup is not currently fully implemented. The line for building it is currently normally commented out. dbGroup is one of our priorities for the coming year. </p>

<p>If you re-comment out the line</p>

<code>#include $(PVASRV_SRC)/dbGroup/Makefile</code>

<p>in src/Makefile then it should build.

**Comment by NickeZ** [comment]
A sorry, didn't realize that I shouldn't compile that.

**Comment by ralphlange** [comment]
The functionality (quasi atomic access to a configurable group of PVs on a standard IOC) will be back, but with a different implementation based on things that Base will provide in upcoming 3.16.
Stay tuned...
