### ISSUE TITLE
pvaSrv fails with base-3.15.3

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvaSrv#22]
Build with base-3.15.3 and then
mrk> pwd
/home/epicsv4/testpvaSrv/pvaSrv/testTop/iocBoot/testDbPv
mrk> ../../bin/linux-x86_64/testDbPv st.cmd 

Then in another window:

mrk> pvlist
GUID 0x55767156000000009812BD07, version 1: tcp@[10.0.0.159:5075]
mrk> pvlist 0x55767156000000009812BD07
[server] connection timeout
mrk>

**Comment by ralphlange** [comment]
Hm. So what is the issue?

**Comment by ralphlange** [comment]
Let me put my question differently:

Using EPICS 3.15 and up, by definition, any IOC with at least one record hosts an infinite number of PVs. (PVs can be any field of any record, extended by any possible configuration combination of server-side plugins.)

Not implementing the pv list functionality is the easiest way to handle this situation.

What reply do you expect from pvlist?
(While you're at it: what would be the answer for the Gateway?)

**Comment by dhickin** [comment]
<p>I considered a similar issue when looking at group operations where I was using the channel name to encode the group. Similar issues arise for any channel derived from other channels, especially where there are infinitely many possible channel names. In the case of the group operation demo I continued returning the underlying simple channel names. I would have guessed pvaSrv would do the equivalent thing - return the list of channels corresponding to the records.</p>

**Comment by ralphlange** [comment]
Returning the record names is definitely possible.
If it is appropriate depends on the exact specification of the pv list feature, which I was not able to find.

Inside a "pure" pvAccess server things might be easier, as the number of channels will often be finite. (Only top level pvData structures are channels.)

I cannot see, however, how something like a Gateway for a large installation (ITER will have a few million records) will ever be able to return something useful. Not implementing this feature (or returning something meaning "too many") must be an option.

**Comment by msekoranja** [comment]
Does "pvlist -i <GUID>" works? 

"a few million records":  Currently in EPICS every record is accessible via network. I think we should have a "visible"/"export" flag that would expose only selected records. From "that million records" only a small percentage needs to be accessible over the network, right?

**Comment by anjohnson** [comment]
When a client sends a pvlist request, does the server know the identity of the client — i.e. does the pvlist client connection go through the pluggable authentication process with the server first? Also is it possible to send any metadata with the pvlist request, such that the user can ask for the just list of PVs for which it has write access, or those that belong to some defined "public API" group.

I can see sites wanting to be able to expose different sets of PVs to different user roles, and users wanting to be able to ask for just writable PVs. Channel access security might be useful in declaring records to be exported or not, but it could also be a *lot* of work for the IOC to check the access permissions for every record record in the database, so this isn't necessarily a desirable thing from the perspective of pvaSrv.

I'm trying to support Ralph in pointing out that the minimalist pvlist functionality by itself doesn't necessarily make very much sense for the IOC database.

**Comment by msekoranja** [comment]
The server knows the identity of the client (IP), goes through security plugin (this can provide more info about the client) and metadata can be sent (pvRequest or as fields in pvStructure). pvlist simply does RPC on a channel. The infrastructure is in place.

pvlist is a dbl equivalent. It's a simple util that I found it useful over last years. I guess Marty uses it too (hence this issue).
It's nothing fancy and that would probably be an overkill for current needs and pvaSrv.

The infrastructure is there and can it is not required to be implemented (a server can return an empty list or even better: return a error/warning status back.)

A note on "exposing" the channels. I was not thinking about different user roles at all. Currently every record in .db is exposed. Records that are there for process logic could be hidden. I wonder: what percentage of records in the system are accessed over the network?

**Comment by mrkraimer** [comment]
I think there is more of a problem than just pvlist.
I ran into the problem while working on
https://github.com/mrkraimer/exampleCPP

This has a number of examples.
Most  examples that implement a server allow the server to be started as a main or as part of a V3 IOC.

When started as a main the only provider is local.
The example works just fine.
When started as part of a V3 IOC the providers are local and dbPv.
I can access all the DB channels via both caget and pvget.
BUT I can not access the PV channels.
If I do not start provider dbPv I can access the PV channels.

Marty

**Comment by anjohnson** [comment]
@msekoranja "what percentage of records in the system are accessed over the network?" — That's going to depend on who is doing the accessing. During development or while diagnosing a problem with the machine an IOC developer will often want to access records and fields that are never meant to be accessed by other parts of the control system or by the machine operators, but those IOC developers are just as much our users as the others. The ability to view the internal workings of the IOC is a powerful thing that other control system tool-kits don't usually support.

**Comment by msekoranja** [comment]
@mrkraimer That was my assumption. It's a multi provider issue.
@anjohnson Thanks Andrew. I am thinking of a discovery mechanism designs and I wanted to get some valuable (in field) info.

**Comment by mdavidsaver** [comment]
I'll second Andrew, being able to peek at the what "internals" is occasionally quite handy.  At the same time it isn't desirable to "advertise" them.

As an example, for nsls2 this was "solved" via naming convention.  Record names ending in '_' don't appear in channel finder listings.

Or perhaps it's time to dust off DBRN_FLAGS_VISIBLE and the record() vs. grecord() distinction?

**Comment by mdavidsaver** [comment]
Personally I would rather see a push rather than a pull strategy to aggregate record lists.  Something like recsync combined with channel finder.  Of course having both isn't bad.

https://github.com/mdavidsaver/recsync

**Comment by mrkraimer** [comment]
The attacked file  provides some  clues about why pvaSrv fails with base 3.15

[base3_15problem.txt](https://github.com/epics-base/pvaSrv/files/67138/base3_15problem.txt)

**Comment by mrkraimer** [comment]
I spend some more time investigating this problem.
I think the problem is access security.

Remember that the example has two providers registered pvaSrv and local.
Accessing a channel provided by pvaSrv works just fine.
When a channel provided by local is requests it the channel is never created

By placing some print statement in pvAccessCPP/src/server/responseHandlers.cpp
I found the following

ServerCreateChannelHandler::handleResponse catch (SecurityException& se calling cr->channelCreated channelName doubleArray

**Comment by mrkraimer** [comment]
The problem appears to be as follows:

If more than one provider is registered an a client attempts to connect to a channel provided by the second provider the connection request fails.

Consider two providers: pvaSrv and local.
pvget attempts to connect to a channel provided by local.
The following sequence of actions occurs:

A channel find is issued to pvaSrv, which fails,
A channel find is issued to local, which succeeds.
A channel create is issued.
For some reason this results in a call to the access security code in pvaSrv, which results on a failure returned to pvget,
