### ISSUE TITLE
How to manipulate data in epics base records?

### ISSUE THREAD

**Issue by izzarasul** [epics-base/pvaSrv#57]
I have two records bi and bo . what i want to to is if bi is given an input 1 bo set to o and vice versa. Need help what should i write in field???

regards,
Izza Rasul

**Comment by ralphlange** [comment]
This issue is unrelated to the pvaSrv software module. Closing.

Please send such questions to the [tech-talk mailing list](https://epics.anl.gov/tech-talk/index.php), which is the appropriate forum.
